---
- name: Check if k8s config file exists
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeconfig_exists

- name: Initialize k8s if config file does not exist
  ansible.builtin.command:
    cmd: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU,Mem
  when: not kubeconfig_exists.stat.exists
  register: kubeadm_output
  changed_when: kubeadm_output.rc == 0

- name: Set permissions for admin.conf
  ansible.builtin.file:
    path: /etc/kubernetes/admin.conf
    mode: "0644"

- name: Create .kube directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"

- name: Copy config files
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: true
  become: true
  register: copy_output
  changed_when: copy_output.changed

- name: Set chmod for config file
  ansible.builtin.file:
    path: ~/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Check if flannel pod exists already
  ansible.builtin.shell:
    cmd: kubectl get pods --all-namespaces | grep kube-flannel
  register: flannel_exists
  ignore_errors: true

- name: Install flannel otherwise
  ansible.builtin.command:
    cmd: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: flannel_exists.rc != 0

- name: Token create join-command
  ansible.builtin.shell:
    cmd: kubeadm token create --print-join-command > join-command.sh
  register: join_command_output
  changed_when: join_command_output.rc == 0
