---
- name: Disable swap
  become: true
  ansible.builtin.command:
    cmd: swapoff -a
  register: swapoff_output
  changed_when: swapoff_output.rc == 0

- name: Install required packages using yum
  become: true
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - kubelet
    - kubeadm

- name: Enable and start services - docker and kubelet
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - docker
    - kubelet
