---
- name: K8s on Control Plane
  hosts: di_controlplane
  become: true

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/k8s_key
    ansible_ssh_common_args:
      -o ProxyCommand='ssh -o StrictHostKeyChecking=no -i ~/.ssh/bastion_host_key -W %h:%p -q ec2-user@{{ hostvars[groups['di_bastion'][0]].ansible_host
      }}'

  roles:
    - install_k8s
    - install_docker_and_co
    - cp_tasks

- name: K8s on Bastion
  hosts: di_bastion
  become: true

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/bastion_host_key
    ansible_ssh_common_args:
      -o ProxyCommand='ssh -o StrictHostKeyChecking=no -i ~/.ssh/bastion_host_key -W %h:%p -q ec2-user@{{ hostvars[inventory_hostname].ansible_host
      }}'

  roles:
    - install_k8s
    - bastion_tasks

- name: K8s on Workers
  hosts: di_worker
  become: true

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/k8s_key
    ansible_ssh_common_args:
      -o ProxyCommand='ssh -o StrictHostKeyChecking=no -i ~/.ssh/bastion_host_key -W %h:%p -q ec2-user@{{ hostvars[groups['di_bastion'][0]].ansible_host
      }}'

  roles:
    - install_k8s
    - install_docker_and_co
    - worker_tasks
